server:
  port: 9084
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8762/eureka/
  instance:
    hostname: localhost
    appname: gateway
    prefer-ip-address: true
spring:
  application:
    name: gateway
#  security:
#    user:
#      name: admin
#      password: admin

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8764/oauth/token
      user-authorization-uri: http://localhost:8764/oauth/authorize
      client-id: webapp
      client-secret: webapp
    resource:
      user-info-uri: http://localhost:8764/api/user
      prefer-token-info: false