server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8762/eureka/
  instance:
    hostname: localhost
    appname: service-provider
    instance-id: service-provider
    prefer-ip-address: true
spring:
  application:
    name: service-provider
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8764/oauth/token
      user-authorization-uri: http://localhost:8764/oauth/authorize
      client-id: webapp
      client-secret: webapp
    resource:
      user-info-uri: http://localhost:8764/uaa/api/user
      #必须设置true
      prefer-token-info: true
      token-info-uri: http://localhost:8764/oauth/check_token
