server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8762/eureka/
  instance:
    hostname: localhost
    appname: admin
    instance-id: admin
    prefer-ip-address: true
spring:
  application:
    name: admin