server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8762/eureka/
  instance:
    hostname: localhost
    appname: uaa
    instance-id: uaa
    prefer-ip-address: true
spring:
  application:
    name: uaa
  security:
    user:
      name: admin
      password: $2a$10$ODoZJKtLmhwpdfeoU08Q7OqrpftHfWpaBGhsRG.Xw4XRk69/RkLR.
#  redis:
#    host: localhost
#    port: 6379

#security:
#  oauth2:
#    resource:
#      filter-order: 3
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
