server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8762/eureka/
  instance:
    hostname: localhost
    appname: uaa
    instance-id: uaa
    prefer-ip-address: true
spring:
  application:
    name: uaa
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379

security:
  oauth2:
    resource:
      filter-order: 3

